### ISSUE TITLE
Cache problem when QueryField type is Object

### ISSUE THREAD

**Issue by rostislavcz** [portiny/portiny#17]
Hi, 

I tried your example for SimpleQueryField from https://github.com/portiny/graphql/blob/master/docs/en/index.md

(I use your Nette implementation)

Everything looks fine, but when I enable schema cache and I change getType function to return ObjectType instead of scalar type, api after that returns null to all data. 

When I manually delete cache, the first request is Ok, but when I do the request again, then it is with null data in each field.

Is there any change you could tell me how to solve this?

**Comment by rostislavcz** [comment]
I think I found the problem,

It is in SchemaCacheProvider in getTypeConfigDecorator function, there is no resolver in default case in switch for ObjectType, there should be probably 
`return ([Executor::class, 'defaultFieldResolver'])($value, $args, $context, $info);`
at the end,

like this:
`private function getTypeConfigDecorator(): Closure
	{
		return function (array $typeConfig) {
			$typeConfig['resolveField'] = function ($value, $args, $context, ResolveInfo $info) use ($typeConfig) {
				$fieldName = (string) $info->fieldName;

				switch ($typeConfig['name']) {
					case 'Query':
						$queryField = $this->queryFieldsProvider->getField($fieldName);
						if ($queryField) {
							return $queryField->resolve($value, $args, $context);
						}
						break;

					case 'Mutation':
						$mutationField = $this->mutationFieldsProvider->getField($fieldName);
						if ($mutationField) {
							return $mutationField->resolve($value, $args, $context);
						}
						break;

					default:
						$type = Types::findByName($typeConfig['name']);
						if ($type instanceof ObjectType) {
							$fieldNameForResolving = $fieldName;
							if ($type->hasField($fieldNameForResolving)) {
								$typeField = $type->getField($fieldNameForResolving);
								$resolver = $typeField->resolveFn;
								if (is_callable($resolver)) {
									return $resolver($value, $args, $context, $info);
								}
							}

							$resolver = $type->resolveFieldFn;
							if (is_callable($resolver)) {
								return $resolver($value, $args, $context, $info);
							}
                            return ([Executor::class, 'defaultFieldResolver'])($value, $args, $context, $info);
						}
				}

				return null;
			};

			$typeConfig['parseValue'] = function ($value) use ($typeConfig) {
				$customType = Types::findByName($typeConfig['name']);
				if ($customType instanceof ScalarType) {
					return $customType->parseValue($value);
				}

				return $value;
			};

			$typeConfig['parseLiteral'] = function ($valueNode, ?array $variables = null) use ($typeConfig) {
				$customType = Types::findByName($typeConfig['name']);
				if ($customType instanceof ScalarType) {
					return $customType->parseLiteral($valueNode, $variables);
				}

				return AST::valueFromASTUntyped($valueNode, $variables);
			};

			return $typeConfig;
		};
	}`

**Comment by TomasPilar** [comment]
Hi @rostislavcz,

thank you for your bug-report. 
The problem should be fixed in tag https://github.com/portiny/portiny/releases/tag/5.0.4.
Please use it and test it. 

Happy programming!
