### ISSUE TITLE
Join us at Contributte

### ISSUE THREAD

**Issue by f3l1x** [portiny/portiny#6]
Hi guys! :tada: 

This post is realted to Nette forum: https://forum.nette.org/cs/29892-vendor-lock-hell-kdyby-doctrine-nette-3-0#p196050

I must appeal to not waste your time to making own fork/implementation of Doctrine, Symfony Console, Symfony EventDispatcher. 

Is it really your solution so different from contributte's ones? Or nettrine's one?

I (and many others at Contributte and Nettrine) will be glad if you join us and make this packages great together. :heart_eyes: 

Please think this properly. :100: 

Thanks.
Felix

**Comment by TomasPilar** [comment]
Hi Felix!

Thank you for invitation into Contributte community. I will think about it after review your packagists. My goal is keep integrations very very simple without any "usefull" magic.
